heat_template_version: newton

description: >
  Vpp service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  VppCpuMainCore:
    default: ''
    description: VPP main thread core pinning.
    type: string
  VppCpuCorelistWorkers:
    default: ''
    description: List of cores for VPP worker thread pinning
    type: string
  MonitoringSubscriptionVpp:
    default: 'overcloud-vpp'
    type: string

outputs:
  role_data:
    description: Role data for the Vpp role.
    value:
      service_name: vpp
      monitoring_subscription: {get_param: MonitoringSubscriptionVpp}
      config_settings:
        # Core pinning is being set in controller_extraconfig and compute_extraconfig to allow
        # role specifc settings
        #fdio::vpp_cpu_main_core: {get_param: VppCpuMainCore}
        #fdio::vpp_cpu_corelist_workers: {get_param: VppCpuCorelistWorkers}
      step_config: |
        include ::tripleo::profile::base::vpp
